name: 'Update internal sources'
description: 'Update the internal sources to the latest.'
inputs:
  version:
    type: string
    required: true
    description: 'The version of the source code'
  github_token:
    type: string
    required: true
    description: 'The GitHub Personal Access Token to use to push changes'
defaults:
  run:
    shell: bash
runs:
  using: "composite"
  steps:
    - name: Merge vanilla sources
      shell: bash
      run: |
        cd Plazma-Server
        cp -r ./.gradle/caches/paperweight/mc-dev-sources/com ./src/main/java/
        cp -r ./.gradle/caches/paperweight/mc-dev-sources/net ./src/main/java/
        cp -r ./.gradle/caches/paperweight/mc-dev-sources/data ./src/main/resources/
        cp -r ./.gradle/caches/paperweight/mc-dev-sources/assets ./src/main/resources/
        cp -r ./.gradle/caches/paperweight/mc-dev-sources/META-INF ./src/main/resources/
        cp -r ./.gradle/caches/paperweight/mc-dev-sources/*.* ./src/main/resources/
        git add .
        git commit --fixup $(git rev-list -n 1 base)
        git rebase --autosquash upstream/master
        cd ..

    - name: Push source changes (API)
      uses: ad-m/github-push-action@master
      with:
        repository: PlazmaMC/sources-api
        directory: ./Plazma-API
        branch: plazma/${{ inputs.version }}
        github_token: ${{ inputs.github_token }}
        force: true

    - name: Push source changes (server)
      uses: ad-m/github-push-action@master
      with:
        repository: PlazmaMC/sources-server
        directory: ./Plazma-Server
        branch: plazma/${{ inputs.version }}
        github_token: ${{ inputs.github_token }}
        force: true
