name: Plazma-Test-Plugin
version: ${version}
main: org.purpurmc.testplugin.TestPlugin
description: Purpur Test Plugin
author: PlazmaMC
api-version: ${apiversion}
load: STARTUP
#bootstrapper: org.plazmamc.testplugin.TestPluginBootstrap
#loader: org.plazmamc.testplugin.TestPluginLoader
defaultPerm: FALSE
permissions:
dependencies:
