on:
  workflow_call:
    secrets:
      GH_PAT:
        required: true
      SIG_JAR_ALIAS:
        required: true
      SIG_JAR_PASS:
        required: true
      SIG_JAR_STORE:
        required: true
      SIG_JAR_STORE_PASS:
        required: true
      SIG_MVN_PGP:
        required: true
      SIG_MVN_PASS:
        required: true

env:
  ORG_GRADLE_PROJECT_ghName: ${{ github.repository_owner }}
  ORG_GRADLE_PROJECT_ghToken: ${{ secrets.GH_PAT }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIG_MVN_PGP }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIG_MVN_PASS }}
  SIGN_KEY_ALIAS: ${{ secrets.SIG_JAR_ALIAS }}
  SIGN_KEY_PASSWORD: ${{ secrets.SIG_JAR_PASS }}
  SIGN_KEYSTORE_DATA: ${{ secrets.SIG_JAR_STORE }}
  SIGN_KEYSTORE_PASSWORD: ${{ secrets.SIG_JAR_STORE_PASS }}

jobs:
  release:
    name: Release Plazma
    strategy:
      matrix:
        base_jdk: [21]
        os: [ubuntu-22.04]

    if: "!startsWith(github.event.commits[0].message, '[CI-Skip]')"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup workflow
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          VERSION="${BRANCH##*/}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BUILDID=$(git ls-remote --tags https://github.com/PlazmaMC/PlazmaBukkit | grep "build/$VERSION" | wc -l)" >> $GITHUB_ENV
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up GraalVM ${{ matrix.base_jdk }}
        uses: graalvm/setup-graalvm@v1
        with:
          github-token: ${{ secrets.GH_PAT }}
          java-version: ${{ matrix.base_jdk }}
          version: latest
          cache: 'gradle'

      - name: Apply Patches
        run: ./gradlew applyPatches --info --stacktrace

      - name: Build Sources
        run: ./gradlew build --info --stacktrace

      - name: Create Re-obfuscated Server Jar
        run: ./gradlew createReobfPaperclipJar --info --stacktrace

      - name: Create Mojang-mapped Server Jar
        run: ./gradlew createMojmapPaperclipJar --info --stacktrace

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: build/libs/*.jar
          if-no-files-found: error
          compression-level: 9

      # - name: Publish Packages
      #   run: ./gradlew publish --info --stacktrace
      #   if: startsWith(github.ref_name, 'ver/') || startsWith(github.ref_name, 'dev/')

      - name: Update internal sources
        uses: PlazmaMC/PlazmaBukkit/.github/actions/sources@main
        with:
          version: ${{ env.VERSION }}
          github_token: ${{ secrets.GH_PAT }}
        if: startsWith(github.ref_name, 'ver/') || startsWith(github.ref_name, 'dev/')

      - name: Update Javadocs
        uses: PlazmaMC/PlazmaBukkit/.github/actions/javadocs@main
        with:
          version: ${{ env.VERSION }}
          github_token: ${{ secrets.GH_PAT }}
        if: startsWith(github.ref_name, 'ver/') || startsWith(github.ref_name, 'dev/')

      - name: Release artifacts
        uses: PlazmaMC/PlazmaBukkit/.github/actions/release@main
        with:
          version: ${{ env.VERSION }}
          development: ${{ startsWith(github.ref_name, 'dev/') }}
          build_number: ${{ env.BUILDID }}
          github_token: ${{ secrets.GH_PAT }}
          discord_webhook: ${{ secrets.WEBHOOK_URL }}
        if: startsWith(github.ref_name, 'ver/') || startsWith(github.ref_name, 'dev/')
