name: Test Gradle build script

on:
  push:
    branches: [ "ver/*", "dev/*", "feat/**/*" ]
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        jdk: [21]
        java: ['zulu']
        os: [ubuntu-22.04]

    if: "!contains(github.event.commits[0].message, '[CheckSkip]')"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout action
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK ${{ matrix.java }} ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.java }}
          java-version: ${{ matrix.jdk }}
          cache: 'gradle'

      - name: Configure Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com" && git config --global user.name "github-actions[bot]"

      - name: Run Gradle
        run: ./gradlew --stacktrace
