name: Release Plazma
run-name: Manual release of Plazma on branch ${{ github.ref_name }}

on:
  push:
    branches: [ "ver/*", "dev/*", "feat/**/*" ]
  workflow_dispatch:

jobs:
  release:
    if: ${{ github.ref_name != "main }}
    name: Release Plazma (${{ github.ref_name }})
    uses: PlazmaMC/PlazmaBukkit/.github/workflows/global.yaml@main
    secrets: inherit
